export const GET_ADVANTAGES_REQUEST = "GET_ADVANTAGES_REQUEST";
export const GET_ADVANTAGES_SUCCESS = "GET_ADVANTAGES_SUCCESS";
export const GET_ADVANTAGES_FAIL = "GET_ADVANTAGES_FAIL";

export const GET_ADVANTAGEDETAIL_REQUEST = "GET_ADVANTAGEDETAIL_REQUEST";
export const GET_ADVANTAGEDETAIL_SUCCESS = "GET_ADVANTAGEDETAIL_SUCCESS";
export const GET_ADVANTAGEDETAIL_FAIL = "GET_ADVANTAGEDETAIL_FAIL";

export const CREATE_ADVANTAGE_REQUEST = "CREATE_ADVANTAGE_REQUEST";
export const CREATE_ADVANTAGE_SUCCESS = "CREATE_ADVANTAGE_SUCCESS";
export const CREATE_ADVANTAGE_FAIL = "CREATE_ADVANTAGE_FAIL";
export const CREATE_ADVANTAGE_RESET = "CREATE_ADVANTAGE_RESET";

export const UPDATE_ADVANTAGE_REQUEST = "UPDATE_ADVANTAGE_REQUEST";
export const UPDATE_ADVANTAGE_SUCCESS = "UPDATE_ADVANTAGE_SUCCESS";
export const UPDATE_ADVANTAGE_FAIL = "UPDATE_ADVANTAGE_FAIL";
export const UPDATE_ADVANTAGE_RESET = "UPDATE_ADVANTAGE_RESET";

export const DELETE_ADVANTAGE_REQUEST = "DELETE_ADVANTAGE_REQUEST";
export const DELETE_ADVANTAGE_SUCCESS = "DELETE_ADVANTAGE_SUCCESS";
export const DELETE_ADVANTAGE_FAIL = "DELETE_ADVANTAGE_FAIL";
export const DELETE_ADVANTAGE_RESET = "DELETE_ADVANTAGE_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
