export const REGISTERCLUBPLAN_REQUEST = "REGISTERCLUBPLAN_REQUEST";
export const REGISTERCLUBPLAN_SUCCESS = "REGISTERCLUBPLAN_SUCCESS";
export const REGISTERCLUBPLAN_FAIL = "REGISTERCLUBPLAN_FAIL";
export const REGISTERCLUBPLAN_RESET = "REGISTERCLUBPLAN_RESET";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
