export const GET_CLUBPLANS_REQUEST = "GET_CLUBPLANS_REQUEST";
export const GET_CLUBPLANS_SUCCESS = "GET_CLUBPLANS_SUCCESS";
export const GET_CLUBPLANS_FAIL = "GET_CLUBPLANS_FAIL";

export const GET_CLUBPLANDETAIL_REQUEST = "GET_CLUBPLANDETAIL_REQUEST";
export const GET_CLUBPLANDETAIL_SUCCESS = "GET_CLUBPLANDETAIL_SUCCESS";
export const GET_CLUBPLANDETAIL_FAIL = "GET_CLUBPLANDETAIL_FAIL";

export const CREATE_CLUBPLAN_REQUEST = "CREATE_CLUBPLAN_REQUEST";
export const CREATE_CLUBPLAN_SUCCESS = "CREATE_CLUBPLAN_SUCCESS";
export const CREATE_CLUBPLAN_FAIL = "CREATE_CLUBPLAN_FAIL";
export const CREATE_CLUBPLAN_RESET = "CREATE_CLUBPLAN_RESET";

export const UPDATE_CLUBPLAN_REQUEST = "UPDATE_CLUBPLAN_REQUEST";
export const UPDATE_CLUBPLAN_SUCCESS = "UPDATE_CLUBPLAN_SUCCESS";
export const UPDATE_CLUBPLAN_FAIL = "UPDATE_CLUBPLAN_FAIL";
export const UPDATE_CLUBPLAN_RESET = "UPDATE_CLUBPLAN_RESET";

export const DELETE_CLUBPLAN_REQUEST = "DELETE_CLUBPLAN_REQUEST";
export const DELETE_CLUBPLAN_SUCCESS = "DELETE_CLUBPLAN_SUCCESS";
export const DELETE_CLUBPLAN_FAIL = "DELETE_CLUBPLAN_FAIL";
export const DELETE_CLUBPLAN_RESET = "DELETE_CLUBPLAN_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
