export const GET_FACILITIES_REQUEST = "GET_FACILITIES_REQUEST";
export const GET_FACILITIES_SUCCESS = "GET_FACILITIES_SUCCESS";
export const GET_FACILITIES_FAIL = "GET_FACILITIES_FAIL";

export const GET_FACILITYDETAIL_REQUEST = "GET_FACILITYDETAIL_REQUEST";
export const GET_FACILITYDETAIL_SUCCESS = "GET_FACILITYDETAIL_SUCCESS";
export const GET_FACILITYDETAIL_FAIL = "GET_FACILITYDETAIL_FAIL";

export const CREATE_FACILITY_REQUEST = "CREATE_FACILITY_REQUEST";
export const CREATE_FACILITY_SUCCESS = "CREATE_FACILITY_SUCCESS";
export const CREATE_FACILITY_FAIL = "CREATE_FACILITY_FAIL";
export const CREATE_FACILITY_RESET = "CREATE_FACILITY_RESET";

export const UPDATE_FACILITY_REQUEST = "UPDATE_FACILITY_REQUEST";
export const UPDATE_FACILITY_SUCCESS = "UPDATE_FACILITY_SUCCESS";
export const UPDATE_FACILITY_FAIL = "UPDATE_FACILITY_FAIL";
export const UPDATE_FACILITY_RESET = "UPDATE_FACILITY_RESET";

export const DELETE_FACILITY_REQUEST = "DELETE_FACILITY_REQUEST";
export const DELETE_FACILITY_SUCCESS = "DELETE_FACILITY_SUCCESS";
export const DELETE_FACILITY_FAIL = "DELETE_FACILITY_FAIL";
export const DELETE_FACILITY_RESET = "DELETE_FACILITY_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
