export const GET_FEATURES_REQUEST = "GET_FEATURES_REQUEST";
export const GET_FEATURES_SUCCESS = "GET_FEATURES_SUCCESS";
export const GET_FEATURES_FAIL = "GET_FEATURES_FAIL";

export const GET_FEATUREDETAIL_REQUEST = "GET_FEATUREDETAIL_REQUEST";
export const GET_FEATUREDETAIL_SUCCESS = "GET_FEATUREDETAIL_SUCCESS";
export const GET_FEATUREDETAIL_FAIL = "GET_FEATUREDETAIL_FAIL";

export const CREATE_FEATURE_REQUEST = "CREATE_FEATURE_REQUEST";
export const CREATE_FEATURE_SUCCESS = "CREATE_FEATURE_SUCCESS";
export const CREATE_FEATURE_FAIL = "CREATE_FEATURE_FAIL";
export const CREATE_FEATURE_RESET = "CREATE_FEATURE_RESET";

export const UPDATE_FEATURE_REQUEST = "UPDATE_FEATURE_REQUEST";
export const UPDATE_FEATURE_SUCCESS = "UPDATE_FEATURE_SUCCESS";
export const UPDATE_FEATURE_FAIL = "UPDATE_FEATURE_FAIL";
export const UPDATE_FEATURE_RESET = "UPDATE_FEATURE_RESET";

export const DELETE_FEATURE_REQUEST = "DELETE_FEATURE_REQUEST";
export const DELETE_FEATURE_SUCCESS = "DELETE_FEATURE_SUCCESS";
export const DELETE_FEATURE_FAIL = "DELETE_FEATURE_FAIL";
export const DELETE_FEATURE_RESET = "DELETE_FEATURE_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
