export const GET_FLOORPLANS_REQUEST = "GET_FLOORPLANS_REQUEST";
export const GET_FLOORPLANS_SUCCESS = "GET_FLOORPLANS_SUCCESS";
export const GET_FLOORPLANS_FAIL = "GET_FLOORPLANS_FAIL";

export const GET_FLOORPLANDETAIL_REQUEST = "GET_FLOORPLANDETAIL_REQUEST";
export const GET_FLOORPLANDETAIL_SUCCESS = "GET_FLOORPLANDETAIL_SUCCESS";
export const GET_FLOORPLANDETAIL_FAIL = "GET_FLOORPLANDETAIL_FAIL";

export const CREATE_FLOORPLAN_REQUEST = "CREATE_FLOORPLAN_REQUEST";
export const CREATE_FLOORPLAN_SUCCESS = "CREATE_FLOORPLAN_SUCCESS";
export const CREATE_FLOORPLAN_FAIL = "CREATE_FLOORPLAN_FAIL";
export const CREATE_FLOORPLAN_RESET = "CREATE_FLOORPLAN_RESET";

export const UPDATE_FLOORPLAN_REQUEST = "UPDATE_FLOORPLAN_REQUEST";
export const UPDATE_FLOORPLAN_SUCCESS = "UPDATE_FLOORPLAN_SUCCESS";
export const UPDATE_FLOORPLAN_FAIL = "UPDATE_FLOORPLAN_FAIL";
export const UPDATE_FLOORPLAN_RESET = "UPDATE_FLOORPLAN_RESET";

export const DELETE_FLOORPLAN_REQUEST = "DELETE_FLOORPLAN_REQUEST";
export const DELETE_FLOORPLAN_SUCCESS = "DELETE_FLOORPLAN_SUCCESS";
export const DELETE_FLOORPLAN_FAIL = "DELETE_FLOORPLAN_FAIL";
export const DELETE_FLOORPLAN_RESET = "DELETE_FLOORPLAN_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
