export const GET_HOMEDATA_REQUEST = "GET_HOMEDATA_REQUEST";
export const GET_HOMEDATA_SUCCESS = "GET_HOMEDATA_SUCCESS";
export const GET_HOMEDATA_FAIL = "GET_HOMEDATA_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_CLUBPLAN_REQUEST = "GET_CLUBPLAN_REQUEST";
export const GET_CLUBPLAN_SUCCESS = "GET_CLUBPLAN_SUCCESS";
export const GET_CLUBPLAN_FAIL = "GET_CLUBPLAN_FAIL";

export const GET_ABOUT_REQUEST = "GET_ABOUT_REQUEST";
export const GET_ABOUT_SUCCESS = "GET_ABOUT_SUCCESS";
export const GET_ABOUT_FAIL = "GET_ABOUT_FAIL";
export const GET_ABOUT_RESET = "GET_ABOUT_RESET";

export const UPDATE_ABOUT_REQUEST = "UPDATE_ABOUT_REQUEST";
export const UPDATE_ABOUT_SUCCESS = "UPDATE_ABOUT_SUCCESS";
export const UPDATE_ABOUT_FAIL = "UPDATE_ABOUT_FAIL";
export const UPDATE_ABOUT_RESET = "UPDATE_ABOUT_RESET";
