export const GET_HOMEDATA_REQUEST = "GET_HOMEDATA_REQUEST";
export const GET_HOMEDATA_SUCCESS = "GET_HOMEDATA_SUCCESS";
export const GET_HOMEDATA_FAIL = "GET_HOMEDATA_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_CLUBPLAN_REQUEST = "GET_CLUBPLAN_REQUEST";
export const GET_CLUBPLAN_SUCCESS = "GET_CLUBPLAN_SUCCESS";
export const GET_CLUBPLAN_FAIL = "GET_CLUBPLAN_FAIL";
