export const GET_MEMBERS_REQUEST = "GET_MEMBERS_REQUEST";
export const GET_MEMBERS_SUCCESS = "GET_MEMBERS_SUCCESS";
export const GET_MEMBERS_FAIL = "GET_MEMBERS_FAIL";

export const GET_MEMBERDETAIL_REQUEST = "GET_MEMBERDETAIL_REQUEST";
export const GET_MEMBERDETAIL_SUCCESS = "GET_MEMBERDETAIL_SUCCESS";
export const GET_MEMBERDETAIL_FAIL = "GET_MEMBERDETAIL_FAIL";

export const CREATE_MEMBER_REQUEST = "CREATE_MEMBER_REQUEST";
export const CREATE_MEMBER_SUCCESS = "CREATE_MEMBER_SUCCESS";
export const CREATE_MEMBER_FAIL = "CREATE_MEMBER_FAIL";
export const CREATE_MEMBER_RESET = "CREATE_MEMBER_RESET";

export const UPDATE_MEMBER_REQUEST = "UPDATE_MEMBER_REQUEST";
export const UPDATE_MEMBER_SUCCESS = "UPDATE_MEMBER_SUCCESS";
export const UPDATE_MEMBER_FAIL = "UPDATE_MEMBER_FAIL";
export const UPDATE_MEMBER_RESET = "UPDATE_MEMBER_RESET";

export const DELETE_MEMBER_REQUEST = "DELETE_MEMBER_REQUEST";
export const DELETE_MEMBER_SUCCESS = "DELETE_MEMBER_SUCCESS";
export const DELETE_MEMBER_FAIL = "DELETE_MEMBER_FAIL";
export const DELETE_MEMBER_RESET = "DELETE_MEMBER_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
