export const GET_PLANBENEFITS_REQUEST = "GET_PLANBENEFITS_REQUEST";
export const GET_PLANBENEFITS_SUCCESS = "GET_PLANBENEFITS_SUCCESS";
export const GET_PLANBENEFITS_FAIL = "GET_PLANBENEFITS_FAIL";

export const GET_PLANBENEFITDETAIL_REQUEST = "GET_PLANBENEFITDETAIL_REQUEST";
export const GET_PLANBENEFITDETAIL_SUCCESS = "GET_PLANBENEFITDETAIL_SUCCESS";
export const GET_PLANBENEFITDETAIL_FAIL = "GET_PLANBENEFITDETAIL_FAIL";

export const CREATE_PLANBENEFIT_REQUEST = "CREATE_PLANBENEFIT_REQUEST";
export const CREATE_PLANBENEFIT_SUCCESS = "CREATE_PLANBENEFIT_SUCCESS";
export const CREATE_PLANBENEFIT_FAIL = "CREATE_PLANBENEFIT_FAIL";
export const CREATE_PLANBENEFIT_RESET = "CREATE_PLANBENEFIT_RESET";

export const UPDATE_PLANBENEFIT_REQUEST = "UPDATE_PLANBENEFIT_REQUEST";
export const UPDATE_PLANBENEFIT_SUCCESS = "UPDATE_PLANBENEFIT_SUCCESS";
export const UPDATE_PLANBENEFIT_FAIL = "UPDATE_PLANBENEFIT_FAIL";
export const UPDATE_PLANBENEFIT_RESET = "UPDATE_PLANBENEFIT_RESET";

export const DELETE_PLANBENEFIT_REQUEST = "DELETE_PLANBENEFIT_REQUEST";
export const DELETE_PLANBENEFIT_SUCCESS = "DELETE_PLANBENEFIT_SUCCESS";
export const DELETE_PLANBENEFIT_FAIL = "DELETE_PLANBENEFIT_FAIL";
export const DELETE_PLANBENEFIT_RESET = "DELETE_PLANBENEFIT_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
