export const GET_PROPERTIES_REQUEST = "GET_PROPERTIES_REQUEST";
export const GET_PROPERTIES_SUCCESS = "GET_PROPERTIES_SUCCESS";
export const GET_PROPERTIES_FAIL = "GET_PROPERTIES_FAIL";

export const GET_PROPERTYDETAIL_REQUEST = "GET_PROPERTYDETAIL_REQUEST";
export const GET_PROPERTYDETAIL_SUCCESS = "GET_PROPERTYDETAIL_SUCCESS";
export const GET_PROPERTYDETAIL_FAIL = "GET_PROPERTYDETAIL_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
