export const GET_PROPERTIES_REQUEST = "GET_PROPERTIES_REQUEST";
export const GET_PROPERTIES_SUCCESS = "GET_PROPERTIES_SUCCESS";
export const GET_PROPERTIES_FAIL = "GET_PROPERTIES_FAIL";

export const GET_PROPERTYDETAIL_REQUEST = "GET_PROPERTYDETAIL_REQUEST";
export const GET_PROPERTYDETAIL_SUCCESS = "GET_PROPERTYDETAIL_SUCCESS";
export const GET_PROPERTYDETAIL_FAIL = "GET_PROPERTYDETAIL_FAIL";

export const CREATE_PROPERTY_REQUEST = "CREATE_PROPERTY_REQUEST";
export const CREATE_PROPERTY_SUCCESS = "CREATE_PROPERTY_SUCCESS";
export const CREATE_PROPERTY_FAIL = "CREATE_PROPERTY_FAIL";
export const CREATE_PROPERTY_RESET = "CREATE_PROPERTY_RESET";

export const UPDATE_PROPERTY_REQUEST = "UPDATE_PROPERTY_REQUEST";
export const UPDATE_PROPERTY_SUCCESS = "UPDATE_PROPERTY_SUCCESS";
export const UPDATE_PROPERTY_FAIL = "UPDATE_PROPERTY_FAIL";
export const UPDATE_PROPERTY_RESET = "UPDATE_PROPERTY_RESET";

export const DELETE_PROPERTY_REQUEST = "DELETE_PROPERTY_REQUEST";
export const DELETE_PROPERTY_SUCCESS = "DELETE_PROPERTY_SUCCESS";
export const DELETE_PROPERTY_FAIL = "DELETE_PROPERTY_FAIL";
export const DELETE_PROPERTY_RESET = "DELETE_PROPERTY_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
