export const GET_QUOTES_REQUEST = "GET_QUOTES_REQUEST";
export const GET_QUOTES_SUCCESS = "GET_QUOTES_SUCCESS";
export const GET_QUOTES_FAIL = "GET_QUOTES_FAIL";

export const GET_QUOTEDETAIL_REQUEST = "GET_QUOTEDETAIL_REQUEST";
export const GET_QUOTEDETAIL_SUCCESS = "GET_QUOTEDETAIL_SUCCESS";
export const GET_QUOTEDETAIL_FAIL = "GET_QUOTEDETAIL_FAIL";

export const CREATE_QUOTE_REQUEST = "CREATE_QUOTE_REQUEST";
export const CREATE_QUOTE_SUCCESS = "CREATE_QUOTE_SUCCESS";
export const CREATE_QUOTE_FAIL = "CREATE_QUOTE_FAIL";
export const CREATE_QUOTE_RESET = "CREATE_QUOTE_RESET";

export const UPDATE_QUOTE_REQUEST = "UPDATE_QUOTE_REQUEST";
export const UPDATE_QUOTE_SUCCESS = "UPDATE_QUOTE_SUCCESS";
export const UPDATE_QUOTE_FAIL = "UPDATE_QUOTE_FAIL";
export const UPDATE_QUOTE_RESET = "UPDATE_QUOTE_RESET";

export const DELETE_QUOTE_REQUEST = "DELETE_QUOTE_REQUEST";
export const DELETE_QUOTE_SUCCESS = "DELETE_QUOTE_SUCCESS";
export const DELETE_QUOTE_FAIL = "DELETE_QUOTE_FAIL";
export const DELETE_QUOTE_RESET = "DELETE_QUOTE_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
